### ISSUE TITLE
How SparseFeature use in your demo?

### ISSUE THREAD

**Issue by Thanh-Binh** [ogmacorp/OgmaNeoDemos#11]
I understood that you use SparseFeatures(STDP, Chunk etc) for encodering the input images and then for predicting.
There is only one place for changing a type of encoder, using header file like
#input <neo/SparseFeaturesSTDP.h>
But I do not understand how this encoder is used internally.
Even by making a comment on this line, e.g. 
//#input <neo/SparseFeaturesSTDP.h>
That means I do not use any SparseEncoder, but it does not matter anything. I can see what will be predicted.
I am not sure if the encoder is used correctly?

Do I understand your algorithm correctly?
Binh

**Comment by rcrowder** [comment]
Hi, The `SparseFeaturesType` [1] is passed as a parameter to `Architect::addHigherLayer` [2] when constructing a hierarchy. The Video_Prediction demo [3] shows how to add multiple layers using different Sparse Feature encoders.

1 https://github.com/ogmacorp/OgmaNeo/blob/master/source/system/ComputeProgram.h#L19
2 https://github.com/ogmacorp/OgmaNeo/blob/master/source/neo/Architect.h#L304
3 https://github.com/ogmacorp/OgmaNeoDemos/blob/master/demos/Video_Prediction.cpp#L70-L114

**Comment by Thanh-Binh** [comment]
Yes. I see.
Why do you use different SF encoder in Video_Prediction? For demo: different layer, different encoders OR for better performance?
