### ISSUE TITLE
Errors in build - Please assit

### ISSUE THREAD

**Issue by AIAdventures** [ogmacorp/OgmaNeoDemos#16]
building on a linux machine- 

andrewcz@andrewcz-PORTEGE-Z30t-B ~/OgmaNeo/build $ cmake -DBUILD_SHARED_LIBS=ON ..
CMAKE_BUILD_TYPE not set, setting it to Release
-- Build type: Release
-- Bitness: 64
-- Shared libs: ON
-- Found existing OpenCL in OPENCL_INCLUDE_DIRS-NOTFOUND
-- Found existing OpenCL lib /usr/lib/x86_64-linux-gnu/libOpenCL.so
-- CL2 HPP not found!
-- Could NOT find flatbuffers (missing:  FLATBUFFERS_FLATC_EXECUTABLE FLATBUFFERS_INCLUDE_DIR) 
-- -- FlatBuffers will be downloaded and built from source
-- Found CL files - neoKernelsSparseFeaturesDistance.cl;neoKernelsSparseFeaturesChunk.cl;neoKernelsHierarchy.cl;neoKernelsPredictor.cl
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OPENCL_INCLUDE_DIRS
   used as include directory in directory /home/andrewcz/OgmaNeo
   used as include directory in directory /home/andrewcz/OgmaNeo
   used as include directory in directory /home/andrewcz/OgmaNeo
   used as include directory in directory /home/andrewcz/OgmaNeo
   used as include directory in directory /home/andrewcz/OgmaNeo
   used as include directory in directory /home/andrewcz/OgmaNeo

-- Configuring incomplete, errors occurred!
See also "/home/andrewcz/OgmaNeo/build/CMakeFiles/CMakeOutput.log".
andrewcz@andrewcz-PORTEGE-Z30t-B ~/OgmaNeo/build $

**Comment by rcrowder** [comment]
Hi @AIAdventures You need to install an OpenCL SDK to meet the requirements of OgmaNeo (https://github.com/ogmacorp/OgmaNeo#requirements)

**Comment by AIAdventures** [comment]
many thanks so i am up to this step and getting the below-

  6%] Performing configure step for 'FlatBuffers'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/andrewcz/OgmaNeo/build/FlatBuffers/src/FlatBuffers-build
[  9%] Performing build step for 'FlatBuffers'
[ 21%] Built target flatbuffers
[ 95%] Built target flatc
[100%] Built target flathash
[ 12%] Performing install step for 'FlatBuffers'
[ 21%] Built target flatbuffers
[ 95%] Built target flatc
[100%] Built target flathash
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/flatc.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/reflection.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/code_generators.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/reflection_generated.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/flatbuffers.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/idl.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/util.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/flexbuffers.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/grpc.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/include/flatbuffers/hash.h
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/lib/libflatbuffers.a
-- Up-to-date: /home/andrewcz/OgmaNeo/build/3rdparty/bin/flatc
[ 15%] Completed 'FlatBuffers'
[ 25%] Built target FlatBuffers
[ 53%] Built target OgmaNeoSchemas
[ 56%] Built target OgmaOCLtoHpp
[ 68%] Built target OgmaOCLtoH
[ 71%] Building CXX object CMakeFiles/OgmaNeo.dir/source/neo/FeatureHierarchy.cpp.o
In file included from /home/andrewcz/OgmaNeo/source/neo/Helpers.h:12:0,
                 from /home/andrewcz/OgmaNeo/source/neo/SparseFeatures.h:12,
                 from /home/andrewcz/OgmaNeo/source/neo/FeatureHierarchy.h:12,
                 from /home/andrewcz/OgmaNeo/source/neo/FeatureHierarchy.cpp:9:
/home/andrewcz/OgmaNeo/source/system/ComputeSystem.h:21:22: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
                      ^
compilation terminated.
make[2]: *** [CMakeFiles/OgmaNeo.dir/source/neo/FeatureHierarchy.cpp.o] Error 1
make[1]: *** [CMakeFiles/OgmaNeo.dir/all] Error 2
make: *** [all] Error 2
andrewcz@andrewcz-PORTEGE-Z30t-B ~/OgmaNeo/build $ 

Would you know to fix the error.
Many thanks,
Andrew

**Comment by rcrowder** [comment]
Yes, the CL2.hpp header file is not part of an OpenCL SDK and needs to be downloaded separately and added to where your OpenCL header files are (https://github.com/ogmacorp/OgmaNeo#cl2-header-file).

**Comment by AIAdventures** [comment]
ah ok, let me try that. i am running a linux mint system

**Comment by AIAdventures** [comment]
thankyou so much for your help

**Comment by AIAdventures** [comment]
so i have tried to locate the header files but I dont really understand what im looking for and where to place the file?
Was wondering if you could assist.
Best,
Andrew

**Comment by rcrowder** [comment]
Where the OpenCL SDK installs it's header files can vary, depending on how the SDK is installed. On Linux systems, the header files typically get placed in `/usr/include/CL` or `/usr/local/include/CL` directories. You're looking for the SDK's cl.h file. The cl2.hpp file needs to be put in the same directory as the cl.h file.

**Comment by AIAdventures** [comment]
your a hero!! will give it another go :).
Many thanks,
Best,
Andrew

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/25895577/d406e6fc-35c3-11e7-9ade-6f61ed47ddd3.png)
so i have found the above.

**Comment by AIAdventures** [comment]
but it does not let me paste the file? for some reason...

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/25895685/457aec66-35c4-11e7-9e32-ea2b59630d1b.png)

**Comment by rcrowder** [comment]
Yes it's a user protected directory. You need to have `root` owner permission to put a file into the directory. One way to do this is to use this Terminal command `sudo cp cl2.hpp /usr/include/CL/cl2.hpp`

**Comment by AIAdventures** [comment]
while the cl2.hpp is saved on my desktop?

**Comment by rcrowder** [comment]
Then the command is likely to be `sudo cp /home/<username>/Desktop/cl2.hpp /usr/include/CL/cl2.hpp` I'm not familiar with Mint (usually use MacOS and Ubuntu), so the Desktop directory may be different.

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/25895978/9f9b36d2-35c5-11e7-98f0-6c6cad17d358.png)

**Comment by AIAdventures** [comment]
success!!!

**Comment by AIAdventures** [comment]
it looks like that worked!!!

**Comment by AIAdventures** [comment]
thanks so much for your help.
have an awesome day :).
Best,
Andrew

**Comment by rcrowder** [comment]
You're welcome, you too. I'll leave this issue open for now in case you have further issues. And close it later today, reopen the issue after that if you need to.

**Comment by AIAdventures** [comment]
so im trying to run the Sinusoidal Prediction 
![image](https://cloud.githubusercontent.com/assets/26102503/25896421/6512cb68-35c7-11e7-9082-1c3853f82221.png)

**Comment by AIAdventures** [comment]
how to i only do this one and not cmake the rest of the demos?
Many thanks again,
Best,
Andrew

**Comment by rcrowder** [comment]
Each demo has their own 'makefile' target that can be used to make them individually. For that demo you can use `make Wavy_Test` (https://github.com/ogmacorp/OgmaNeoDemos#sinusoidal-prediction).

**Comment by AIAdventures** [comment]
Inside the demos folder?
Best,
Andrew

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/25896610/4453d04c-35c8-11e7-9de2-3e3b76d1af86.png)

**Comment by AIAdventures** [comment]
i get the above running make Wavy_Test

**Comment by rcrowder** [comment]
Hmm :( Looks like the SFML library has finally depreciated that function.. Will investigate further.

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/25896743/bf03fb3c-35c8-11e7-832d-7be079d695e8.png)

**Comment by AIAdventures** [comment]
clearer photo :)
thank you..champion!
Best,
Andrew

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/25896987/8f53bf20-35c9-11e7-9bfa-c156c3141403.png)

**Comment by rcrowder** [comment]
I've checked Linux Mint 18.1 and it uses SFML v2.3.2 when installed via Aptitude (apt-get). The current demos use more a more recent version of SFML (v2.4.x). The calls to `setFillColor` would need to be replaced with the older `setColor` calls on your local build. Or you can uninstall the older SFML, and install the latest version from the SFML website.
The `No platforms found.` error from the demo shows that your graphics driver is either not installed or not up to date.

**Comment by AIAdventures** [comment]
ok two step is to install latest SFML and update graphics cards

**Comment by AIAdventures** [comment]
would there be an easy "sudo" process for this?

**Comment by rcrowder** [comment]
Rather than uninstalling the existing SFML library, you can let the OgmaNeoDemos CMake build download it for you. To do this you would edit the CMakeLists.txt file.
On this line https://github.com/ogmacorp/OgmaNeoDemos/blob/master/CMakeLists.txt#L127 you would change it to `find_package(SFML 2.4 COMPONENTS system window graphics audio)`

After making that change you would need to clean your cmake cache (delete your CMakeFiles directory and CMakeCache.txt file). Then you can re-run `cmake .` You should see the following;
> SFML found but version too low (requested: 2.4, found: 2.3)
> -- -- SFML will be downloaded and built from source

This change will be in a future patch of the demos, I wasn't aware that SFML 2.3 is still a default installation in certain Linux flavours, such as Mint. Good to know.

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/25996247/c20007da-3759-11e7-945c-5d045f57d9fe.png)

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/25996307/14f0d3ca-375a-11e7-852a-d22c5565b1bd.png)

**Comment by AIAdventures** [comment]
So trying your advice and getting the above.
Best,
Andrew

**Comment by rcrowder** [comment]
Hey, building SFML from source requires certain library dependencies [1] One way to sort them out in this case is with -  `sudo apt install libxcb-image0-dev libudev-dev libopenal-dev libvorbis-dev libflac-dev`

1 https://www.sfml-dev.org/tutorials/2.4/compile-with-cmake.php#installing-dependencies

**Comment by rcrowder** [comment]
Btw; There is a known outstanding issue with SFML built from source as a shared library using G++ v5 compiler :( [1] Workarounds exists, but require patching of SFML CMake build file.

I'm looking to see if a PPA is available for easily updating SFML to version 2.4 on Linux Mint (e.g. [2]). Or for yourself, whether to bite the bullet and show how to purge existing SFML and build latest SFML from source..

1 https://en.sfml-dev.org/forums/index.php?topic=20638.0
2 https://www.ubuntuupdates.org/ppa/getdeb_apps

**Comment by rcrowder** [comment]
For example;
> sudo apt purge libsfml-dev
> sudo apt autoremove
> wget https://www.sfml-dev.org/files/SFML-2.4.0-linux-gcc-64-bit.tar.gz
> tar xvf SFML-2.4.0-linux-gcc-64-bit.tar.gz
> cd SFML-2.4.0
> sudo cp -r . /usr/local/

**Comment by AIAdventures** [comment]
ah very good!
I have done the above and get the following-

**Comment by AIAdventures** [comment]
![screenshot_2017-05-13_09-19-37](https://cloud.githubusercontent.com/assets/26102503/26020024/5d43c822-37bd-11e7-9c39-8e2f21f3db0e.png)

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/26020196/126513fe-37bf-11e7-9b89-34d291f38a05.png)

**Comment by rcrowder** [comment]
One of the main issues here has been the different versions of the SFML library. Linux Mint only offers pre-build SFML 2.3, but the demos use version 2.4 What you are now seeing are differences between v2.4.0 and v2.4.2 The demos need to be updated to the latest SFML 2.4.2 library, so I'm creating a hot-fix patch that'll update the code for that. I should have that pushed to here on Monday.
In the meantime, you will also need to address the issue of getting OpenCL to work in your install of Linux Mint. The `clinfo` utility can tell you when it is setup correctly. It's going to need you to update graphics drivers. Hopefully the graphics card you are using is capable of running OpenCL v1.2?

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/26032733/d8e08454-38dd-11e7-8111-ec5f7e354f78.png)

**Comment by AIAdventures** [comment]
Ah thanks!
i ran the tool you recommended and got the above.
Will try and do some install for intels opencl sdk for linux.
This should get better results.

**Comment by AIAdventures** [comment]
![image](https://cloud.githubusercontent.com/assets/26102503/26032752/40bcff8a-38de-11e7-8c07-d1c2d9b3fa73.png)

**Comment by rcrowder** [comment]
@AIAdventures I'm closing this issue. It relates to missing requirements/dependencies for OgmaNeo and the demos (namely correct version SFML, and a working OpenCL SDK).
