### ISSUE TITLE
Request: basic demo

### ISSUE THREAD

**Issue by HJLebbink** [ogmacorp/OgmaNeoDemos#4]
Request: could you please provide a basic demo that does nothing fancy but just loads some numbers from file, does some learning, and spits out some numbers to the console. In other words, could you make a demo with only necessary dependencies. I like to study a Feynman machine without begin distracted by e.g. opencv, SFML etc.

The last two days I have been trying to get the two demo to work, and I failed.

Regards Henk-Jan.

**Comment by rcrowder** [comment]
Hello @HJLebbink,
This is a good suggestion. I'm sorry to hear that you have had issues getting the existing demos working. It'd be great to hear about the issues you have faced.
We are planning to make a release next week, and add to that release a simple sequence demo (similar to the https://github.com/ogmacorp/PyOgmaNeo examples).

**Comment by HJLebbink** [comment]
Hi @Richard,
I've tried a x86 debug build with VS2015. I think I've setup OpenCV and SFML correctly, but since I don't have a proper GPU, I use the "Intel SDK for OpenCL - CPU Only Runtime".  The MNIST demo crashes after calling clEnqueueReadImage. Eventually I like to run this on a Xeon Phi.

Question: what version of OpenCL are you using? Have you tried it on _cpu only mode?

Regards HJ!

**Comment by rcrowder** [comment]
@HJLebbink Thank you. That is very useful information.

We use and require  version 1.2 of OpenCL. Our testing on _cpu and _gpu devices, so far, has included the following combinations:
- AMD APP SDK 3.0 on Windows and Linux
- NVIDIA CUDA SDK 7.5 and 8.x on Windows, Linux, and Mac
- Portable OpenCL (POCL) on Raspberry Pi3 (CPU only)

I'm currently setting up Travis CI to automate building and testing. Travis uses Google Compute Engines with Intel CPUs. I've been setting that up to use POCL for CPU only testing, but will definitely investigate using the Intel OpenCL SDK (using Khronos Group's ICD loaded for side-by-side comparison with POCL).

**Comment by rcrowder** [comment]
@HJLebbink We released a version this week, v1.0.1, that addresses a couple of issues seen with certain vendor OpenCL compilers. This included testing with the Intel OpenCL SDK. We believe that that release should help address the issue you saw with the demos. I'm now looking at producing a simple C++ example as you suggest.
