### ISSUE TITLE
Agent demo

### ISSUE THREAD

**Issue by HJLebbink** [ogmacorp/OgmaNeoDemos#6]
@rcrowder Thank you for providing the sequence recall demo, much appreciated. As I was building my own demo I was wondering if an agent demo is available. Again, it does not need to be fancy, nor state of the art; working code would be enough to study the idea.

Btw, I'm really impressed with the small memory footprint and fast training of this particular method.

**Comment by jaridekker** [comment]
i second this, i am impressed by the demo's so far, and would love to see and be able to experiment with an implementation of the RL agent. this would show the capabilities of the system a lot better in my opinion.

**Comment by rcrowder** [comment]
Hi @HJLebbink and @Barie Although we currently expose a swarming agent in the OgmaNeo library, we do consider it work in progress. We agree that a demo for that or an alternative agent should exist. I can't guarantee when that demo will be produced. Currently we are working on a new release of the main OgmaNeo library. Introducing further enhancements to it and particularly how hierarchies are generated.

**Comment by jaridekker** [comment]
ah @rcrowder, very nice to hear that progress is being made. thanks for the update, you guys do promising work here, Looking forward to more documentation and examples to use this in predicting/learning/bots/robotics :). What would especially be useful is a little expanding documentation on the optimal data structures for input/output/reward variables, especially as your software is so fundamentally different from most others.

**Comment by HJLebbink** [comment]
Hi @rcrowder, yes this is a refreshing approach which makes guessing parameters a but of a challenge. I don't want to delay the ongoing progress. Also looking forward to a new release.
